### ISSUE TITLE
[FEATURE REQUEST] reCAPTCHA for subscribe form

### ISSUE THREAD

**Issue by nbeck415** [ephemeralenvironments/ephemeralenvironments#25]
**Is your feature request related to a problem? Please describe.**

Spam bots are finding the subscribe form and submitting fake emails

**Describe the solution you'd like**

Ideally, this would add onto the existing inline JS to add a Google reCAPTCHA 2 to the subscribe form. Don't worry about getting an API key, I have one I can sub in later. 

Since we use Netlify for deployment, server side verification will be done via them [if you use the correct fields](https://docs.netlify.com/forms/spam-filters/#custom-recaptcha-2). You will still have to implement client side logic.

Ping me if you have any questions
 
**List alternatives you've considered**

A short list of any alternative solutions or features you've considered.
N/A

**Additional context**

Check out the form on the https://shipyard.build homepage for a working example

**Assign to self**

Check this box if you'd like to take on the issue:

- [ ] I would like to work on this issue

**Comment by creaturenex** [comment]
I would like to give this a try.

**Comment by nbeck415** [comment]
@creaturenex thanks! Will assign to you

**Comment by creaturenex** [comment]
Sorry for the delay, will try to tackle this in the next few days.

**Comment by creaturenex** [comment]
Netlify has recaptcha v2 built in, why don't we leverage this? It would allow you to use the Netlify dashboard. I haven't used it personally. I am unsure if your team is leveraging it for this static site, or want to building the verification logic if you ever move from Netlify.

I have an example from the shipyard homepage and saw that you are using google v2. I want to make sure we are aligned on the path forward.
[Netlify recaptcha](https://docs.netlify.com/forms/spam-filters/#custom-recaptcha-2)

**Research**
Netlify already has recaptcha built in
- uses v2
- allows for custom recaptcha which would allow you to use google recaptcha v2, based on forum, might be able to use v3 or enterprise for more granular control

[Netlify Hugo Forms](https://answers.netlify.com/t/support-guide-creating-netlify-forms-in-hugo/84261)
[Netlify Form Debugging](https://answers.netlify.com/t/support-guide-form-problems-form-debugging-404-when-submitting/92)

**Alternative**
hCaptcha - more privacy focus
- [hcaptcha privacy policy](https://www.hcaptcha.com/privacy)
- Not currently supported by Netlify
  
- While currently not supported, seem like you can pass it through and handle the verification on your end
  - [Netlify forum passed through hcaptcha](https://answers.netlify.com/t/form-containing-hcaptcha-response-always-returns-303/83742/2)

**Comment by nbeck415** [comment]
Hi @creaturenex, all good questions. I have implemented the logic on the Shipyard static site, so I can answer any questions.

Yes, netlify has recaptcha support built in, but it wasn't sufficient for our use case. I believe this was because we wanted to support multiple recaptchas at a time and have more access to the recaptcha response data (however this was awhile ago and my memory on it is fuzzy). 

Implementing recaptcha without using the netlify toggle would make it easier for you to test, as you would put the Google sitekeys directly in the form instead of in the netlify env vars section and then see the recaptcha locally (if you set `localhost` as a supported domain on the recaptcha site key settings page). 

At that point, it would be amazing to try hcaptcha, if you are up for it. I think something like that is more aligned with our mission on EE.io, and it's always nice to try something new. What are your thoughts?

**Comment by creaturenex** [comment]
Works for me, I will implement the custom recaptcha, nice to understand the design decision on the previously implemented feature. I will reach out if I run into any issues.

Once I get that working, will submit a new issue to tackle the hcaptcha workflow.
