### ISSUE TITLE
[FEATURE REQUEST] Refactor footer into partial

### ISSUE THREAD

**Issue by nbeck415** [ephemeralenvironments/ephemeralenvironments#31]
**Is your feature request related to a problem? Please describe.**

There are two identical versions of the footer. One on `index.html` and one in `footer.html`. To keep things consistent, it would be great to modify and just use the footer partial on all pages.

**Describe the solution you'd like**

Add footer partial to homepage. Modify existing partial to make it as similar as possible to the existing footer. Build & run locally to ensure it looks/performs like existing footer.

**List alternatives you've considered**

A short list of any alternative solutions or features you've considered.
N/A

**Additional context**

You should be able to run locally with the `hugo serve` command

**Assign to self**

Check this box if you'd like to take on the issue:

- [ ] I would like to work on this issue

**Comment by k1nho** [comment]
Hi 👋 @nbeck415 , I will take this one

**Comment by nbeck415** [comment]
Thanks @k1nho, that'd be great!
