### ISSUE TITLE
[BUG] Double horizontal scrollbar on mobile quote section

### ISSUE THREAD

**Issue by nbeck415** [ephemeralenvironments/ephemeralenvironments#32]
**Describe the bug**

When opening the site on mobile, there's a double scrollbar on the quote section. Ideally we would just have the lower one, as one of them is functionally useless.

**To Reproduce**

1. Go to site on mobile or on extra narrow browser on desktop
2. Scroll sideways on quotes section

**Expected behavior**

There will only be one scrollbar of reasonable length and correct scroll speed

**Additional context**

This might be something to fix in CSS

**Assign to self**

- [ ] I would like to work on this issue

**Comment by gcho91** [comment]
I see the dark grey scroll bar. To clarify, do you just not want to see that grey bar?

![image](https://github.com/ephemeralenvironments/ephemeralenvironments/assets/19658964/a8e96872-1a82-410e-84ca-a058a0bf7101)

**Comment by gcho91** [comment]
Can I take this? I'm really close to a fix and testing them on Chrome/Firefox/Safari

**Comment by nbeck415** [comment]
Awesome, yes will assign to you!
