### ISSUE TITLE
[FEATURE REQUEST] Refactor subscribe form JS, move to separate file

### ISSUE THREAD

**Issue by nbeck415** [ephemeralenvironments/ephemeralenvironments#34]
**Is your feature request related to a problem? Please describe.**

The subscribe form currently uses inline JS in the subscribe partial. We want to minimize inline JS. Can we port this out to a separate file? 

**Describe the solution you'd like**

Create a `subscribe.js` file using the JS found in `subscribe.html` and connect it to the current subscribe partial.

**List alternatives you've considered**

N/A

**Additional context**

It would be great if you could test it on Firefox and Chrome

**Assign to self**

- [ ] I would like to work on this issue

**Comment by nbeck415** [comment]
tagging you here @k1nho so I can assign this to you

**Comment by k1nho** [comment]
Yep, I'll take this one
