### ISSUE TITLE
[FEATURE REQUEST] Update documentation to include basic build and setup instructions

### ISSUE THREAD

**Issue by gcho91** [ephemeralenvironments/ephemeralenvironments#36]
**Is your feature request related to a problem? Please describe.**

Feature request - it would be nice to see basic instructions on how to get the project up and running. For example, I saw this repo on an open source community, and it took me quite a while of digging around to figure out that you needed to get Hugo set up with its own dependencies, and then run `hugo server` from the main directory to get the project up and running locally. This instruction was not in the `CONTRIBUTING.md` file, which is where I would expect this info to be.

**Describe the solution you'd like**

Add basic build and setup instructions on `CONTRIBUTING.md` and anywhere else so anyone wanting to jump into contributing can quickly set up project.

**List alternatives you've considered**

A short list of any alternative solutions or features you've considered.
- N/A

**Additional context**

N/A

**Assign to self**

Check this box if you'd like to take on the issue:

- [ ] I would like to work on this issue

**Comment by nbeck415** [comment]
@gcho91 thanks for opening this! I agree -- all contributors could benefit from some good setup instructions. It would be great to also get a short section in `README.md`. Would you like to take this issue?

**Comment by gcho91** [comment]
Yes - I can attempt this since I went through the process of setting up as a first timer. Please feel free to assign.

**Comment by nbeck415** [comment]
@gcho91 awesome, much appreciated!

**Comment by nbeck415** [comment]
Closed with #38
