### ISSUE TITLE
[FEATURE REQUEST] Add Docker Compose setup instructions

### ISSUE THREAD

**Issue by nbeck415** [ephemeralenvironments/ephemeralenvironments#42]
**Is your feature request related to a problem? Please describe.**

This is an enhancement. We now have a Docker + Docker Compose file, and it would be nice to direct users to developing using Compose.

**Describe the solution you'd like**

Add a line or so to the `CONTRIBUTING.md` file above the hugo instructions. Might make sense as a list? Might want to include:
- link to Docker download (now bundled with Compose)
- running with `docker compose up`
- using provided link to access dev server

**List alternatives you've considered**
N/A

**Additional context**

Try running this project with Docker first to see if there are any nuances you might want to include!

**Assign to self**

- [ ] I would like to work on this issue

**Comment by creaturenex** [comment]
I would like to take this on :)

**Comment by nbeck415** [comment]
Thanks @creaturenex!

**Comment by creaturenex** [comment]
@nbeck415 Can you review this so we can close this out?

**Comment by creaturenex** [comment]
awesome thanks!
