### ISSUE TITLE
[FEATURE REQUEST] Add a quote from Neal 

### ISSUE THREAD

**Issue by nealgroothuis** [ephemeralenvironments/ephemeralenvironments#59]
Per a recent conversation with Benjie, I'd be happy to add a photo/quote touting ephemeral environments :-)

"Ephemeral environments allow me to develop and demo changes quickly and confidently.  They're a huge efficiency booster for any software engineering organization of non-trivial size."

**Assign to self**

Check this box if you'd like to take on the issue:

- [x] I would like to work on this issue

**Comment by nbeck415** [comment]
Thank you, @nealgroothuis! Looking forward to seeing this on the site :)

**Comment by nealgroothuis** [comment]
@nbeck415 Can you grant me privs so I can push a branch and open a PR? :-)

**Comment by nbeck415** [comment]
@nealgroothuis added!

**Comment by nbeck415** [comment]
Thanks @nealgroothuis for getting this live!
